spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service1
          uri: lb://service1
          predicates:
            - Path=/service1/**
          filters:
            - RewritePath=/service1/(?<segment>.*),/$\{segment}
        - id: service2
          uri: lb://service2
          predicates:
            - Path=/service2/**
          filters:
            - RewritePath=/service2/(?<segment>.*),/$\{segment}
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.56.103:8858
      scg:
        fallback:
          mode: response
          response-status: 426
          response-body: '{"code": 426,"message": "限流"}'
          content-type: application/json
      datasource:
        gw-ds1:
          nacos:
            server-addr: 192.168.56.103:8848
            username: nacos
            password: nacos
            rule-type: gw_flow
            data-type: json
            data-id: ${spring.application.name}-gw-rules
        gw-api-ds1:
          nacos:
            server-addr: 192.168.56.103:8848
            username: nacos
            password: nacos
            rule-type: gw_api_group
            data-type: json
            data-id: ${spring.application.name}-gw-api-rules